import Foundation

extension String {
    /// Resolves against Dimera's in-app language override (`AppLanguage`),
    /// not just the device's system language. SwiftUI's `Text("literal")`
    /// automatically picks up `.environment(\.locale)` set at the app root,
    /// but plain Swift code in `Models/` sits outside that view tree and
    /// needs this to follow the same override — every user-facing string
    /// generated by model code should route through this, not the plain
    /// `String(localized:)` initializer.
    ///
    /// Passing `locale:` alone to `String(localized:locale:)` only affects
    /// how interpolated *arguments* format (numbers, dates) — it does NOT
    /// override which `.lproj` bundle the string itself is looked up in,
    /// which still follows the device's own preferred languages. To
    /// actually override the string's own language, the specific `.lproj`
    /// bundle has to be located and queried directly.
    static func localized(_ value: String.LocalizationValue) -> String {
        let language = AppLanguage.current
        guard language != .system,
              let path = Bundle.main.path(forResource: language.rawValue, ofType: "lproj"),
              let languageBundle = Bundle(path: path) else {
            // .system (or a missing .lproj, e.g. English — the source
            // language has no lproj of its own) falls back to the device's
            // own preferred-language resolution, which is already correct.
            return String(localized: value, locale: language.locale)
        }
        return String(localized: value, bundle: languageBundle, locale: language.locale)
    }
}
